article/urls.py
from django.conf.urls import url
from . import views
from django.urls import path ,re_path

app_name = 'article'

urlpatterns = [
    url('article_create/', views.ArticleCreate.as_view(), name = 'article_create'),

    #how to use common regular expressions url in diffrent situation:
    # https://www.codingforentrepreneurs.com/blog/common-regular-expressions-for-django-urls/
    re_path(r'^(?P<slug>[\w-]+)/$', views.ArticleDetail.as_view(), name='article_detail'),

    re_path(r'^update/(?P<slug>[\w-]+)/$', views.ArticleUpdate.as_view(), name='article_update'),

    re_path(r'^delete/(?P<slug>[\w-]+)/$', views.ArticleDelete.as_view(), name='article_delete'),

]

post/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'post'

urlpatterns = [
    url('user_post/', views.PostView.as_view(), name= 'user_post'),
    url('post_list/', views.PostList.as_view(), name='post_list'),

    # DetailView url is represent in the post ID, meaning type in the id of the post
    # and show the detail of the specific post, that what DetailView do, for viewing detail of a model.
    # example if you type /post/4 it will take you to the ID 4 post
    # and you can customize the detail you want to show in the detail.html.
    path('<int:pk>', views.PostDetail, name= 'post_detail'),
    path('update/<int:pk>/', views.PostUpdate, name= 'post_update'),

    #django like button RedirectView
    path('<int:pk>/like/', views.PostLikeToggle.as_view(), name= 'like_toggle'),


    ]

testing_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from user_profile import views

# for displayng images or files when u click the images in the database
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('user_profile/', include('user_profile.urls' , namespace='user_profile')),
    path('post/', include('post.urls', namespace='post')),
    path('article/', include('article.urls', namespace='article')),
    # url specific for following user
    path('follow/', views.ProfileFollowerToggle.as_view(), name= 'follow'),
    # Home feed from user_profile.views
    path('home/', views.HomeFeedView.as_view(), name = 'home-feed'),
    # post rest api
    path('api/post/',include('post.api.urls', namespace='post-api')),
    # comment rest api
    path('api/comment/',include('comment.api.urls', namespace='comment-api')),
    # accounts rest api
    path('api/accounts/',include('accounts.api.urls', namespace='accounts-api')),

    # to use the auth app we need to add it to our project-level urls.py file.
    # like django.contrib.auth built in LoginView
    #https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/
    path('accounts/', include('django.contrib.auth.urls')),
    # add django-ckeditor URLs to sitewide urls.py file.
    path('ckeditor/', include('ckeditor_uploader.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ** for displayng images or files when u click the images in the database**

user_profile/urls.py
from django.conf.urls import url
from . import views
from django.urls import path



app_name = 'user_profile'

urlpatterns = [
    url('profile/', views.UserProfileView.as_view(), name='profile'),
    url('edit/', views.UserProfileEdit, name = 'edit'),
    path('<int:pk>', views.UserProfileDetail, name = 'profile_detail'),
    url('follower/', views.FollowerView.as_view(), name = 'follower'),

]

user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


# Follow user toggle manager
# https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s 'at time 7:08:32'
class UserExtraModelManager(models.Manager):
    def toggle_follow(self, request_user, username_to_toggle):
        get_profile = UserExtraModel.objects.get(user__username__iexact = username_to_toggle)
        user = request_user
        is_following = False
        if user in get_profile.follower.all():
            get_profile.follower.remove(user)
        else:
            get_profile.follower.add(user)
            is_following = True
        return get_profile, is_following



class UserExtraModel(models.Model):
    #inherit the User model pk
    # the related name is use for the model that you get ForeignKey inherit the field inside this models
    user = models.OneToOneField(User, on_delete = models.CASCADE ,related_name = 'userextramodel')
    follower = models.ManyToManyField(User,blank=True, related_name ='is_following')
    image = models.ImageField(upload_to='profile_pics', blank=True)
    description = models.CharField(max_length= 250,default= '')
    city = models.CharField(max_length=250,default= '')
    website = models.URLField(blank= True,default= '')
    contact = models.CharField(max_length=100, blank= True,default= '')

    objects = UserExtraModelManager()

    def __str__(self):
        return self.user.username

# we will now define signals so our Profile model will be automatically created/updated
# when we create/update User instances.
def create_profile(sender, instance, created, *args, **kwargs):
    if created:
        # "instance" means the new user that register
        new_user = UserExtraModel.objects.create(user=instance)

        # Follow User
        # How to make super user Auto following every new user when they create their account
        # https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s "Follow Users (6:33:28)"
        # first, get the super_user
        super_user = UserExtraModel.objects.get(user__username='giam')
        # second, add the "instance" also = "new_user" to our super_user every time when they is a new user register
        super_user.follower.add(instance)

        # Auto following 'super_user' when new_user create account/profile
        instance_user_profile = UserExtraModel.objects.get(user=instance)
        instance_user_profile.follower.add(super_user.user)

        # Auto following themself when they create/register a account
        instance_user_profile = UserExtraModel.objects.get(user=instance)
        instance_user_profile.follower.add(instance_user_profile.user)
post_save.connect(create_profile, sender = User)

user_profile/forms.py
from django.contrib.auth.models import User
from django import forms
from user_profile.models import UserExtraModel
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm

#the advantage of using UserChangeForm is it provide the field like password cannot be edit
# and also provide a message if you want to change password.
class EditForm(UserChangeForm):

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'email', "password")

#make another forms for extra profile imformation
class UserExtraForm(forms.ModelForm):

    class Meta():
        model = UserExtraModel
        fields = ('image','description','city','website','contact')

user_profile/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.urls import reverse
from django.views.generic import TemplateView, ListView, View
from user_profile.forms import EditForm, UserExtraForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect


#listview
from post.models import PostModel
from article.models import ArticleModel
from django.contrib.auth.models import User
from .models import UserExtraModel



class UserProfileView(TemplateView):
    template_name = "user_profile/profile.html"

    def get(self,request):
        # ** RAW LISTVIEW **
        # this line grab all the objects in the PostModel and filter it by the user who currently using
        # or login
        # https://stackoverflow.com/questions/38471260/django-filtering-by-user-id-in-class-based-listview
        user_post_list = PostModel.objects.filter(user= self.request.user)
        user_post_article = ArticleModel.objects.filter(user = self.request.user)
        user_follower_count = UserExtraModel.objects.get(user = self.request.user)
        user_following_count = User.objects.get(username = self.request.user)
        context = { 'user_post_list': user_post_list,
                    'user_post_article':user_post_article,
                    'user_follower_count' :user_follower_count,
                    "user_following_count": user_following_count,}
        return render(request,self.template_name,context)



# this function (request) can access the user profile that login, so type
# {'user':request.user} can access the data of the user.
# if you just want to access the pk, we can type  user_dict = {'user':request.user.pk}
# https://www.youtube.com/watch?v=NhNmQcnv1ms&list=PLw02n0FEB3E3VSHjyYMcFadtQORvl1Ssj&index=17
def UserProfile(request):
     user_dict = {'user':request.user}
     return render(request,'user_profile/profile.html',user_dict)

def UserProfileEdit(request):

    if request.method == 'POST':
        form_edit = EditForm(request.POST, instance= request.user)

        # instance = request.user.userextraprofile mean pass the input to form_extra
        # if you want to save any file or images, must have request.FILES THEN EVERYTHING WILL BE OK!
        form_extra = UserExtraForm(request.POST, request.FILES ,instance= request.user.userextramodel)

        if form_edit.is_valid() and form_extra.is_valid():
            form_edit.save()
            form_extra.save()
            return redirect('/user_profile/profile')
    else:

        form_edit = EditForm(instance = request.user)
        # the purpose instance = request.user.userextraprofile is to fill out the field with data that
        #get from that database with the partiular user that currently using.
        form_extra = UserExtraForm(instance = request.user.userextramodel)
        user_edit = {'form_edit':form_edit,'form_extra':form_extra}
    return render(request,'user_profile/profile_edit.html',context=user_edit)


# Follow Button view
# we handle the logic in "ProfileFollowerToggle" instead of inside "UserProfileDetail" because you cant get the correct
# username with "user_to_toggle = request.POST.get("username")" in the "UserProfileDetail".
# if you handle the logic in "UserProfileDetail", yours **request.POST.get("username")** will run throught one time first
# and get the result of 'None' before clicking the follow-btn, result-in you cant get the "username" of the user that you to follow.
# **So handle the logic with creating a new "View" WILL LEAD THE "username" THAT YOU WANT TO GET PASSING THROUGH THE "URL" EVENTUALLY
# TO THIS "ProfileFollowerToggle" View. **
class ProfileFollowerToggle(View):

    # https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s "Follow Button Form (6:53:30)"
    def post(self,request, *args,**kwargs):
        username_to_toggle = request.POST.get("username")
        get_profile, is_following = UserExtraModel.objects.toggle_follow(request.user, username_to_toggle)
        return redirect(f'/user_profile/{get_profile.user.id}')


def UserProfileDetail(request,pk):

    # link all the user post and article with "related_name" in the PostModel
    # and ArticleModel
    user_info = get_object_or_404(User, pk=pk)
    context ={}
    context['user_info'] = user_info
    context['request_user'] = request.user.username


    # **the purpose of authenticated "request.user" is to avoid error when non-user get into the
    # UserProfileDetail page. Because without login,
    # django dont know who is request.user and it will raising error **
    if request.user.is_authenticated == True :

    # the purpose of this part is to verify the "user_info objects" is being following by the "request.user" anot
    # and get the result to put it in the form for toggle between "Follow" and "Unfollow".
    # https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s "Follow Button Form (6:53:30)"
        is_following = False
        if user_info.userextramodel in request.user.is_following.all():
            is_following = True
            context['is_following'] = is_following

    return render(request, 'user_profile/profile_detail.html', context)

# Follower HomeFeed
# https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s (43 - Following Home Page Feed (7:12:55))
class HomeFeedView(View):

    def get(self, request, *args, **kwargs):
        user = request.user
        is_following_user_id = [x.user.id for x in user.is_following.all()]
        '''
        list=[]
        for x in user.is_following.all():
            list.append(x.user.id)
        '''
        Post_feed = PostModel.objects.filter(user__id__in = is_following_user_id).order_by('-update_at')[:7] # "[:7]" means limit the number of post at 7
        Article_feed = ArticleModel.objects.filter(user__id__in = is_following_user_id).order_by('-updated')[:7]

        context = {'Post_feed':Post_feed, 'Article_feed':Article_feed}
        return render(request, 'user_profile/HomeFeed.html', context)


class FollowerView(View):

    # this part get the request.POST from the profile.html "follower form" throught url that link to 
    # this particular view to process it
    def post(self, request, *args, **kwargs):
        context = {}
        if "follower" in request.POST:
            follower = UserExtraModel.objects.get(user = self.request.user)
            all_follower = follower.follower.all()
            context['all_follower'] = all_follower
        elif "following" in request.POST:
            user = User.objects.get(username = self.request.user)
            all_following = user.is_following.all()
            context['all_following'] = all_following
        # elif 'username' in request.POST:
        #     # print(request.POST)
        #     # print(request.POST.get('username'))
        #     username_to_toggle = request.POST.get("username")
        #     get_profile, is_following = UserExtraModel.objects.toggle_follow(request.user, username_to_toggle)
        #     return redirect('home')
        return render(request,'user_profile/follower.html',context)

user_profile/templates/user_profile/HomeFeed.html
{% extends 'base.html'%}

{% block content %}

<div class="jumbotron">
 <h1>HomeFeed: The user that you follow </h1>
</div>

<h1> Home:</h1>
{% for post in Post_feed %}
  <div class="img-thumbnail" style="width:30%; height:450px; float:left; margin:0 0 20px 3%;">
    <img src="{{ post.file.url }}" alt="sorry" class="img-fluid" style="width:100%;height:70%;">

    {# link the title to the UpdateView and also get the pk for update the specific post #}
    {# https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp/learn/v4/t/lecture/6735078?start=0 #}
    <h4><a href="{% url 'post:post_detail' post.pk %}">{{post.title}}</a></h4>
    <p> <strong><a href="{% url 'user_profile:profile_detail' post.user.id  %}">{{ post.user }}</a></strong> {{post.description|truncatechars:50}} </p>
    <p> Publish at : {{ post.update_at|timesince }} ago</p>
  </div>
{% endfor %}

<h1>My Article:</h1>
{% for article in Article_feed %}
  <div class="row" style="float:left; width:100%; height:300px; border:1px solid black; margin-bottom:30px; " >
    <img src="{{ article.file_url|default_if_none:'#' }}" alt="file missing" style=" width:25%; height:100%;">
    <div class="" style="margin-left:5%;">
      <h1><a href="{% url 'article:article_detail' article.slug %}">{{article.title}}</a></h1>
      <p>{{article.description}}</p>
      <br><br><br>
      <p> <strong><a href="{% url 'user_profile:profile_detail' article.user.id  %}">{{ article.user }}</a></strong> </p>
      <p>{{article.updated|timesince}}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}

user_profile/templates/user_profile/follower.html
{% extends 'base.html'%}

{% block content %}

<div class="jumbotron">

  {% if all_follower %}
    <div class=" col-sm-4 mx-auto">
    <h1>Follow by:</h1>

    <ul>
      {% for follower in all_follower %}
        <li><p>{{follower}}</p></li>
        {# <form class="" action="{% url 'user_profile:follower' %}" method="post">{% csrf_token %} #}
          {# <input type="hidden" name="username" value="{{follower}}" > #}
          {# <button class=" btn {% if is_following %}btn-primary{% else %}btn-success{% endif %}"> #}
              {# {% if is_following %} #}
                {# Unfollow #}
                {# {% else %} #}
                {# Follow #}
              {# {% endif %} #}
          {# </button> #}
        {# </form> #}
      {% endfor %}
    </ul>
    </div>
  {% endif %}



  {% if all_following %}
    <div class=" col-sm-4 mx-auto">
      <h1>I am Following:</h1>
      <ul>
          {% for following in all_following %}
            <li><p>{{following}}</p></li>
          {% endfor %}
    </ul>
    </div>
  {% endif %}

</div>

{% endblock %}

user_profile/templates/user_profile/profile.html
{% extends 'base.html'%}

{% block content %}

<h1>welcome to user profile page!</h1>

<div class="jumbotron">
  <ul>
    <li><h3>Follower: {{user_follower_count.follower.count}} users</h3></li>
    <li><h3>Following: {{user_following_count.is_following.count}} users</h3></li>
    <li>Username: {{user.username}}</li>
    <li>First Name: {{user.first_name}}</li>
    <li>Last Name: {{user.last_name}}</li>
    <li>Email Address: {{user.email}}</li>
    {# because userextraprofile model is link with the user model pk, so type user.userextraprofile.something #}
    {% if user.userextramodel.description%}
    <li>Description: {{user.userextramodel.description}}</li>
    {% endif %}

    {% if user.userextramodel.city %}
    <li>Location: {{user.userextramodel.city}}</li>
    {% endif %}

    {% if user.userextramodel.website %}
    <li>Website: {{user.userextramodel.website}}</li>
    {% endif %}

    {% if user.userextramodel.contact %}
    <li>Contact: {{user.userextramodel.contact}}</li>
    {% endif %}


    {# when displaying file or images in the html, add .url at behind to fetch the images url in the #}
    {# database, but for this to work, adding +static in the project urls.py to connect them together #}
    {# https://docs.djangoproject.com/en/1.8/howto/static-files/#serving-static-files-during-development #}
    {% if user.userextramodel.image %}
    <li>Profile Picture: <br> <img src="{{ user.userextramodel.image.url }}" alt=" sorry " height="250"width="240"></li>
    {% endif %}
  </ul>

  {# following and follower check form/btn #}
  <div class="" style="position:absolute;">
    {# this form send the request.POST to the action=" url ", and the view will get the request wether  #}
    {# is "follower" or "following" and process it. #}
    <form class="" action="{% url 'user_profile:follower' %}" method="post">{% csrf_token %}
    <input style="font-size:20px;" type="submit" class="btn-primary" name="follower" value="Follower">
    <input style="font-size:20px;" type="submit" class="btn-success" name="following" value="Following">
    </form>
  </div>
</div>
    {# userprofile button #}
    {# <a href="{% url 'user_profile:edit' %}"> <input type="submit" class="btn btn-primary" value="Edit"></a> #}
    {# <a href="{% url 'post:user_post' %}" > <input type="submit"  class="btn btn-success btn-outline-success " value="AddPost"></a> #}

    {# <div class="" style="float:right;" > #}
      {# <a href="{% url 'article:article_create' %}" > <input type="submit"  class="btn btn-success btn-outline-success " value="Write Article"></a> #}
    {# </div> #}
    {# </div> #}
  {# ******* #}

    <h1> My Post:</h1>
    {% for post in user_post_list %}
      <div class="img-thumbnail" style="width:30%; height:450px; float:left; margin:0 0 20px 3%;">
        <img src="{{ post.file.url }}" alt="sorry" class="img-fluid" style="width:100%;height:70%;">

        {# link the title to the UpdateView and also get the pk for update the specific post #}
        {# https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp/learn/v4/t/lecture/6735078?start=0 #}
        <h4><a href= "{% url 'post:post_update' pk=post.pk %}" >{{post.title}}</a></h4>
        <p> <strong>{{ post.user }}</strong> {{post.description|truncatechars:50}} </p>
        <p> Publish at : {{ post.update_at|timesince }} ago</p>
      </div>
    {% endfor %}



  <h1>My Article:</h1>
  {% for article in user_post_article %}
    <div class="row" style="float:left; width:100%; height:300px; border:1px solid black; margin-bottom:30px; " >
      <img src="{{ article.file_url|default_if_none:'#' }}" alt="file missing" style=" width:25%; height:100%;">
      <div class="" style="margin-left:5%;">
        <h1><a href= "{% url 'article:article_update' slug=article.slug %}" >{{article.title}}</a></h1>
        <p>{{article.description}}</p>
        <br><br><br>
        <p> <strong>{{ article.user }}</strong> </p>
        <p>{{article.updated|timesince}}</p>
      </div>
    </div>
  {% endfor %}


{% endblock %}

user_profile/templates/user_profile/profile_detail.html
{% extends 'base.html'%}

{% block content %}

<div class="jumbotron">
  <ul>

    {# if you use "get" to get the object in the database, no need to use iterable method  #}
    {# like {% for ** in ** %}, just user the template tag name #}
    <li>Username: {{user_info.username}}</li>
    <li>First Name: {{user_info.first_name}}</li>
    <li>Last Name: {{user_info.last_name}}</li>
    <li>Email Address: {{user_info.email}}</li>
    {# because userextraprofile model is link with the user model pk, so type user.userextraprofile.something #}
    {% if user_info.userextramodel.description%}
    <li>Description: {{user_info.userextramodel.description}}</li>
    {% endif %}

    {% if user_info.userextramodel.city %}
    <li>Location: {{user_info.userextramodel.city}}</li>
    {% endif %}

    {% if user_info.userextramodel.website %}
    <li>Website: {{user_info.userextramodel.website}}</li>
    {% endif %}

    {% if user_info.userextramodel.contact %}
    <li>Contact: {{user_info.userextramodel.contact}}</li>
    {% endif %}


    {# when displaying file or images in the html, add .url at behind to fetch the images url in the #}
    {# database, but for this to work, adding +static in the project urls.py to connect them together #}
    {# https://docs.djangoproject.com/en/1.8/howto/static-files/#serving-static-files-during-development #}
    {% if user_info.userextramodel.image %}
    <li>Profile Picture: <br> <img src="{{ user_info.userextramodel.image.url }}" alt=" sorry " height="250"width="240"></li>
    {% endif %}
  </ul>

  {% if user.is_authenticated %}
  {# if user of this profile_detail page is not the user that login, only the follow button will be show, to prevent the user follow themself #}
  {% if user_info.username != request_user %}
  {# follow form/btn #}
  {# # https://www.youtube.com/watch?v=yDv5FIAeyoY&t=23608s "Follow Button Form (6:53:30)" #}
  <form class="" action="{% url 'follow' %}" method="post">{% csrf_token %}
    <input type="hidden" name="username" value="{{user_info.username}}" >
    <button class=" btn {% if is_following %}btn-primary{% else %}btn-success{% endif %}">
        {% if is_following %}
          Unfollow
          {% else %}
          Follow
        {% endif %}
    </button>
  </form>
{% endif %}
{% endif %}


</div>

<h1> My Post:</h1>
{% for post in user_info.postmodel.all %}
  <div class="img-thumbnail" style="width:30%; height:450px; float:left; margin:0 0 20px 3%;">
    <img src="{{ post.file.url }}" alt="sorry" class="img-fluid" style="width:100%;height:70%;">

    {# link the title to the UpdateView and also get the pk for update the specific post #}
    {# https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp/learn/v4/t/lecture/6735078?start=0 #}
    <h4><a href="{% url 'post:post_detail' post.pk %}">{{post.title}}</a></h4>
    <p> <strong>{{ post.user }}</strong> {{post.description|truncatechars:50}} </p>
    <p> Publish at : {{ post.update_at|timesince }} ago</p>
  </div>
{% endfor %}

<h1>My Article:</h1>
{% for article in user_info.articlemodel.all %}
  <div class="row" style="float:left; width:100%; height:300px; border:1px solid black; margin-bottom:30px; " >
    <img src="{{ article.file_url|default_if_none:'#' }}" alt="file missing" style=" width:25%; height:100%;">
    <div class="" style="margin-left:5%;">
      <h1><a href="{% url 'article:article_detail' article.slug %}">{{article.title}}</a></h1>
      <p>{{article.description}}</p>
      <br><br><br>
      <p> <strong>{{ article.user }}</strong> </p>
      <p>{{article.updated|timesince}}</p>
    </div>
  </div>
{% endfor %}

{% endblock %}

user_profile/templates/user_profile/profile_edit.html
{% extends 'base.html'%}
{% load bootstrap3 %}
{% load staticfiles %}

{% block content %}
<div class="container">
  <h1>User Profile Edit</h1>

   {# ** enctype='multipart/form-data' is for the ImageField and FileField** #}
  {# (cannot save the images or file if enctype is missing)  #}
  <form  method="POST"  enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form_edit %}
    {% bootstrap_form form_extra %}
    <input type="submit" class="btn btn-default" value="Confirm">

  </form>
</div>

{% endblock %}