accounts/urls.py
from django.conf.urls import url
from . import views

#FOR LoginView AND LogoutView
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url('register/', views.RegisterView.as_view(), name='register'),

    # django built in LoginView help us with login without creating a actual view, because login views
    # is too common, so django have built in already.( with database authentication )
    # just supply the template should be render, and the default template tag is {{form}}.
    url("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),

    # LogoutView doesnt need a template to render because logout can just redirect to home
    url("logout/", auth_views.LogoutView.as_view(),name='logout'),

]

article/urls.py
from django.conf.urls import url
from . import views
from django.urls import path ,re_path

app_name = 'article'

urlpatterns = [
    url('article_create/', views.ArticleCreate.as_view(), name = 'article_create'),

    #how to use common regular expressions url in diffrent situation:
    # https://www.codingforentrepreneurs.com/blog/common-regular-expressions-for-django-urls/
    re_path(r'^(?P<slug>[\w-]+)/$', views.ArticleDetail.as_view(), name='article_detail'),

    re_path(r'^update/(?P<slug>[\w-]+)/$', views.ArticleUpdate.as_view(), name='article_update'),

    re_path(r'^delete/(?P<slug>[\w-]+)/$', views.ArticleDelete.as_view(), name='article_delete'),

]

post/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
app_name = 'post'

urlpatterns = [
    url('user_post/', views.PostView.as_view(), name= 'user_post'),
    url('post_list/', views.PostList.as_view(), name='post_list'),

    # DetailView url is represent in the post ID, meaning type in the id of the post
    # and show the detail of the specific post, that what DetailView do, for viewing detail of a model.
    # example if you type /post/4 it will take you to the ID 4 post
    # and you can customize the detail you want to show in the detail.html.
    path('<int:pk>', views.PostDetail, name= 'post_detail'),
    path('update/<int:pk>/', views.PostUpdate, name= 'post_update'),

    #django like button RedirectView
    path('<int:pk>/like/', views.PostLikeToggle.as_view(), name= 'like_toggle'),


    ]

testing_project/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView
from user_profile import views

# for displayng images or files when u click the images in the database
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/',include('accounts.urls',namespace = 'accounts')),
    path('user_profile/', include('user_profile.urls' , namespace='user_profile')),
    path('post/', include('post.urls', namespace='post')),
    path('article/', include('article.urls', namespace='article')),
    # url specific for following user
    path('follow/', views.ProfileFollowerToggle.as_view(), name= 'follow'),
    # Home feed from user_profile.views
    path('home/', views.HomeFeedView.as_view(), name = 'home-feed'),
    # post rest api
    path('api/post/',include('post.api.urls', namespace='post-api')),
    # comment rest api
    path('api/comment/',include('comment.api.urls', namespace='comment-api')),
    # accounts rest api
    path('api/accounts/',include('accounts.api.urls', namespace='accounts-api')),

    # to use the auth app we need to add it to our project-level urls.py file.
    # like django.contrib.auth built in LoginView
    #https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/
    path('accounts/', include('django.contrib.auth.urls')),
    # add django-ckeditor URLs to sitewide urls.py file.
    path('ckeditor/', include('ckeditor_uploader.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # ** for displayng images or files when u click the images in the database**

user_profile/urls.py
from django.conf.urls import url
from . import views
from django.urls import path



app_name = 'user_profile'

urlpatterns = [
    url('profile/', views.UserProfileView.as_view(), name='profile'),
    url('edit/', views.UserProfileEdit, name = 'edit'),
    path('<int:pk>', views.UserProfileDetail, name = 'profile_detail'),
    url('follower/', views.FollowerView.as_view(), name = 'follower'),

]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <!-- {# javascript and CSS for bootstrap 4 #} -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- semantic-ui framework -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script>

    <!-- {# google fonts #} -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <!-- {# css file #} -->
    <link rel="stylesheet" href="{% static 'cinemagraph_social_project/CSS/master.css'%}">

    <!-- ballon ckeditor -->
    <script src="https://cdn.ckeditor.com/ckeditor5/11.0.1/balloon/ckeditor.js"></script>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

   </head>

    <title>Cinemagraph </title>
  </head>
  <body>

    <!-- {# navigationbar #} -->
    <nav  class="navbar navbar-expand-lg navbar-light bg-light" id='navbar' >
      <div class="container">
        <a class="navbar-brand" href="{% url 'home'%}">Article</a>


        <ul class="navbar-nav navbar-right">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'post:post_list' %}">Explore</a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home-feed' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
          
            <!-- profile dropdown -->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.username}}</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'user_profile:profile' %}">My Profile</a>
                  <a class="dropdown-item" href="{% url 'user_profile:edit' %}">Edit Profile</a>
                  <a class="dropdown-item" href="{% url 'post:user_post' %}">Post</a>
                  <a class="dropdown-item" href="{% url 'article:article_create' %}">Write Article</a>
                </div>
              </li>
              <!-- ******* -->
            {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'accounts:register' %}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container ">

      {% block content%}

      {% endblock %}
    </div>


<script type="text/javascript">
// {# for showing reply using toggle button #}
// https://www.youtube.com/watch?v=cLyd8Mx2qak&index=17&list=PLEsfXFp6DpzQB82YbmKKBy2jKdzpZKczn
$(".comment-reply-btn").click(function(event){
       event.preventDefault();
       $(this).parent().next(".comment-reply").fadeToggle();
   })
</script>


  <!-- ckeditor ballon  -->
  <script>
      BalloonEditor
          .create( document.querySelector( '#editor' ) )
          .catch( error => {
              console.error( error );
          } );
  </script>

  </body>
</html>

templates/index.html
{% extends 'base.html'%}

{% block content%}

  <div class="jumbotron">
    <h1>Welcome to Cinemagraph !</h1>
  </div>

  {# search article #}
  <div class="" style="float:right;">
    <form class=""  method="get">
      <input type="text" name="q" value="" placeholder="Search Article">
      <input type="submit" name="" value="Search">
    </form>
  </div>


  <h2>Check out our user article:</h2><br>
  {% for article in article_list %}
  <div class="row" style="float:left; width:100%; height:300px; border:1px solid black; margin-bottom:30px;" >
    <img src="{{ article.file_url|default_if_none:'#' }}" alt="file missing" style=" width:25%; height:100%;">
    <div class="" style="margin-left:5%;">
    <h1><a href= "{% url 'article:article_detail' slug=article.slug %}" >{{article.title}}</a></h1>
    <p>{{article.description}}</p>
    <br><br><br>
      {# to get the user id of the specific article: type "article.user.id" and #}
     {# it will get the user id of this article and pass it to  #}
     {# the 'user_profile':profile_detail' views and render it to show you the detailview. #}
    <p> <strong><a href="{% url 'user_profile:profile_detail' article.user.id  %}">{{ article.user }}</a></strong> </p>
    <p>{{article.updated|timesince}}</p>
    </div>
  </div>

  {% endfor %}





{% endblock %}

templates/test.html
{% extends 'base.html'%}
{% load bootstrap3 %}

{% block content %}
<h1> you are now logged in!</h1>
{% endblock%}

templates/thanks.html
{% extends 'base.html'%}
{% load bootstrap3 %}

{% block content %}
<h1> Thank for visiting ,come back soon!</h1>
{% endblock%}